insert into theaters (name_theater, address_theater) values ('Cinéma du Nord', '50924 Springview Center');
insert into theaters (name_theater, address_theater) values ('Cinéma de Mâcon', '86984 West Way');
insert into theaters (name_theater, address_theater) values ('Cinéma de Marseille 8', '02728 Alpine Crossing');
insert into theaters (name_theater, address_theater) values ('Cinéma de Lyon', '2733 Coolidge Center');
insert into theaters (name_theater, address_theater) values ('Cinéma de Bordeaux', '49710 Meadow Valley Plaza');
insert into theaters (name_theater, address_theater) values ('Cinéma de Toulouse', '93080 Thompson Junction');
insert into theaters (name_theater, address_theater) values ('Cinéma de Lille', '4529 Bunting Drive');
insert into theaters (name_theater, address_theater) values ('Cinéma de Sancé', '7 Hooker Park');
insert into theaters (name_theater, address_theater) values ('Cinéma de Marseille 11', '63705 Buell Alley');
insert into theaters (name_theater, address_theater) values ('Cinéma de Marignane', '31 Brown Crossing');
insert into theaters (name_theater, address_theater) values ('Cinéma de Vitrolles', '5 Monterey Park');
insert into theaters (name_theater, address_theater) values ('Cinéma de Gardanne', '5494 Eastlawn Junction');
insert into theaters (name_theater, address_theater) values ('Cinéma de Lambesc', '4087 Mcguire Terrace');
insert into theaters (name_theater, address_theater) values ('Cinéma de Ventabren', '3215 Sauthoff Hill');
insert into theaters (name_theater, address_theater) values ('Cinéma de Velaux', '9 Derek Avenue');
insert into theaters (name_theater, address_theater) values ('Cinéma de Eguilles', '42 Welch Plaza');
insert into theaters (name_theater, address_theater) values ('Cinéma de Aix En Provence', '0399 Kim Center');
insert into theaters (name_theater, address_theater) values ('Cinéma Avignon', '0391 Badeau Drive');
insert into theaters (name_theater, address_theater) values ('Cinéma de Paris', '0 Knutson Alley');
